# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-16 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
