# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20170517_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(blank=True, upload_to='django-test'),
        ),
    ]
